import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/PageParts";

export const metadata: Metadata = { title: "3-Year Limited Product Warranty", description: "Hidriving limited product warranty overview.", robots: { index: false, follow: true } };

export default function WarrantyPage() {
  return <><PageHero eyebrow="Warranty overview" title="3-Year Limited Product Warranty" text="Covers eligible defects in materials and workmanship, subject to installation, operating and regional warranty terms." /><section className="section"><div className="container narrow legal-copy"><div className="notice"><strong>Publication status</strong><p>This English page is a non-indexed website overview. Final regional legal terms require review for the actual sales market and transaction type before contractual or public use.</p></div><h2>Eligible products and conditions</h2><p>The confirmed policy applies to eligible screw-type supercharger kits from the effective delivery date, subject to documented product identification, installation, operation, maintenance and claim requirements.</p><h2>General coverage</h2><p>Where inspection confirms an eligible material, manufacturing or assembly defect, Hidriving may provide repair, replacement or another applicable remedy under the complete policy and sales agreement.</p><h2>Important exclusions and review points</h2><ul><li>Incorrect installation, unauthorized modification or calibration outside the agreed configuration.</li><li>Racing, track, rally, drifting or sustained extreme operation unless expressly identified otherwise.</li><li>Normal wear, maintenance items and damage caused by external vehicle systems.</li><li>Engine and other vehicle-component claims require evidence, inspection and causal assessment; regional mandatory law may affect any limitation.</li></ul><h2>Claims</h2><p>Keep purchase and delivery evidence, product model and serial number, installation records, photos, video, fault data and relevant maintenance records. Stop using the vehicle when a serious abnormal condition appears.</p><h2>Regional rights</h2><p>Commercial warranty benefits do not remove statutory rights that cannot lawfully be excluded. United States, EU/EEA, United Kingdom, Australia and B2B trade terms require separate regional review.</p><p><Link className="button" href="/contact">Contact After-Sales Support</Link></p></div></section></>;
}
